# Generated by Django 4.2.6 on 2023-10-14 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0002_roles'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='roles',
            table='roles',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuarios',
        ),
    ]
