# Generated by Django 4.2.6 on 2023-11-20 06:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0002_detalleventa_precio_unitario_repuesto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='precioTotal',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.0'), editable=False, max_digits=10),
        ),
    ]
