# Generated by Django 4.2.6 on 2023-11-20 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0003_alter_venta_preciototal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleventa',
            options={},
        ),
        migrations.AlterModelTable(
            name='detalleventa',
            table=None,
        ),
    ]
