# Generated by Django 4.2.6 on 2023-11-20 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0004_alter_detalleventa_options_alter_detalleventa_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='detalleventa',
            table='DetalleVenta',
        ),
    ]
