# Generated by Django 4.2.6 on 2023-10-16 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0007_remove_usuario_esgerente_alter_usuario_idusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motor', models.CharField(max_length=100)),
                ('transmision', models.CharField(max_length=100)),
                ('suspension', models.CharField(max_length=100)),
                ('llanta', models.CharField(max_length=100)),
                ('carroceria', models.CharField(max_length=100)),
                ('electrico', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'CategoriaRepuestos',
                'db_table': 'CategoriaRepuesto',
            },
        ),
        migrations.CreateModel(
            name='PermisoRutas',
            fields=[
                ('idPermiso', models.AutoField(primary_key=True, serialize=False)),
                ('rolId', models.SmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'permisoRutas',
                'db_table': 'permisoRutas',
            },
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('repuestoId', models.AutoField(primary_key=True, serialize=False)),
                ('nombreRepuesto', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('unidades', models.PositiveIntegerField()),
                ('precio', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Repuesto',
                'db_table': 'Repuesto',
            },
        ),
        migrations.CreateModel(
            name='Rutas',
            fields=[
                ('idRuta', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Rutas',
                'db_table': 'Rutas',
            },
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rolId',
            field=models.ForeignKey(blank=True, db_column='rolId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='modulos.roles'),
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('OrdenId', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=100)),
                ('nombreCliente', models.CharField(max_length=100)),
                ('telefonoCliente', models.PositiveIntegerField()),
                ('correo', models.CharField(max_length=100)),
                ('jefeTallerid', models.PositiveBigIntegerField()),
                ('descripcion', models.CharField(max_length=100)),
                ('fechainicio', models.CharField(max_length=100)),
                ('fechaFinal', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('idUsuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modulos.roles')),
            ],
            options={
                'verbose_name_plural': 'OrdenTrabajo',
                'db_table': 'OrdenTrabajo',
            },
        ),
    ]
