# Generated by Django 4.2.6 on 2023-10-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0008_categoriarepuesto_permisorutas_repuesto_rutas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioVehiculo',
            fields=[
                ('invVehiculoId', models.AutoField(primary_key=True, serialize=False)),
                ('vehiculoId', models.PositiveIntegerField()),
                ('sucursalId', models.PositiveIntegerField()),
                ('cantidad', models.PositiveIntegerField()),
            ],
        ),
    ]
