# Generated by Django 4.2.6 on 2023-10-16 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0010_alter_inventariovehiculo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioRepuesto',
            fields=[
                ('invRepuestolId', models.AutoField(primary_key=True, serialize=False)),
                ('repuestoId', models.PositiveIntegerField()),
                ('sucursalId', models.PositiveIntegerField()),
                ('cantidad', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': 'InventarioRepuesto',
                'db_table': 'InventarioRepuesto',
            },
        ),
    ]
