# Generated by Django 4.2.6 on 2023-10-16 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0012_cotizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='precioTotal',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='fechaFabriacion',
            field=models.CharField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='rutas',
            name='nombreRuta',
            field=models.CharField(default='Sin nombre'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(default='Sin dirección'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.CharField(default='example@example.com'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.IntegerField(default=1234567890),
        ),
    ]
