# Generated by Django 4.2.6 on 2023-10-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0014_detalleventa_sucursal_vehiculo_venta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roles',
            old_name='rolId',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='idUsuario',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
