# Generated by Django 4.2.5 on 2023-10-17 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0014_detalleventa_sucursal_vehiculo_venta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roles',
            old_name='rolId',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='rolId',
            new_name='rol',
        ),
        migrations.RemoveField(
            model_name='categoriarepuesto',
            name='carroceria',
        ),
        migrations.RemoveField(
            model_name='categoriarepuesto',
            name='electrico',
        ),
        migrations.RemoveField(
            model_name='categoriarepuesto',
            name='llanta',
        ),
        migrations.RemoveField(
            model_name='categoriarepuesto',
            name='motor',
        ),
        migrations.RemoveField(
            model_name='categoriarepuesto',
            name='suspension',
        ),
        migrations.RemoveField(
            model_name='categoriarepuesto',
            name='transmision',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='usuarioId',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='vehiculoId',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='nombreVehiculo',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='vehiculoId',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='ventaId',
        ),
        migrations.RemoveField(
            model_name='inventariorepuesto',
            name='repuestoId',
        ),
        migrations.RemoveField(
            model_name='inventariorepuesto',
            name='sucursalId',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='idUsuario',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='jefeTallerid',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='idUsuario',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='vendedor',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='vendedorId',
        ),
        migrations.AddField(
            model_name='categoriarepuesto',
            name='tipoRepuesto',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modulos.usuario'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='vehiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modulos.vehiculo'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='vehiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modulos.vehiculo'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='venta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modulos.venta'),
        ),
        migrations.AddField(
            model_name='inventariorepuesto',
            name='repuesto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modulos.repuesto'),
        ),
        migrations.AddField(
            model_name='inventariorepuesto',
            name='sucursal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modulos.sucursal'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='jefeTaller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modulos.usuario'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modulos.usuario'),
        ),
        migrations.AlterField(
            model_name='permisorutas',
            name='rolId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.roles'),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='nombreRepuesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modulos.categoriarepuesto'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='idUsuario',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
