# Generated by Django 4.2.6 on 2023-10-16 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0015_rename_rolid_roles_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='rolId',
            new_name='rol',
        ),
    ]
