# Generated by Django 4.2.5 on 2023-10-17 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0015_rename_rolid_roles_id_rename_rolid_usuario_rol_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventariovehiculo',
            options={},
        ),
        migrations.RemoveField(
            model_name='inventariovehiculo',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='inventariovehiculo',
            name='sucursalId',
        ),
        migrations.RemoveField(
            model_name='inventariovehiculo',
            name='vehiculoId',
        ),
        migrations.AddField(
            model_name='inventariovehiculo',
            name='vehiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modulos.vehiculo'),
        ),
        migrations.AlterModelTable(
            name='inventariovehiculo',
            table=None,
        ),
    ]
