# Generated by Django 4.2.5 on 2023-10-17 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0016_alter_inventariovehiculo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventariovehiculo',
            options={'verbose_name_plural': 'InventarioVehiculo'},
        ),
        migrations.AlterModelTable(
            name='inventariovehiculo',
            table='InventarioVehiculo',
        ),
    ]
