# Generated by Django 4.2.6 on 2023-10-16 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0017_remove_ordentrabajo_idusuario_ordentrabajo_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='usuario',
        ),
    ]
