# Generated by Django 4.2.5 on 2023-10-17 01:16

from django.db import migrations, models
import modulos.models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0018_remove_inventariorepuesto_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutas',
            name='nombreRuta',
            field=models.CharField(default='Sin nombre', verbose_name=modulos.models.PermisoRutas),
        ),
    ]
