# Generated by Django 4.2.6 on 2023-10-16 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0019_remove_usuario_rol_ordentrabajo_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisorutas',
            name='rolId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulos.roles'),
        ),
    ]
