# Generated by Django 4.2.5 on 2023-10-17 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0019_alter_rutas_nombreruta'),
    ]

    operations = [
        migrations.AddField(
            model_name='permisorutas',
            name='rutas',
            field=models.ManyToManyField(to='modulos.rutas'),
        ),
        migrations.AlterField(
            model_name='rutas',
            name='nombreRuta',
            field=models.CharField(default='Sin nombre'),
        ),
    ]
