# Generated by Django 4.2.6 on 2023-10-20 03:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0020_permisorutas_rutas_alter_rutas_nombreruta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleventa',
            old_name='subtotal',
            new_name='precio',
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha',
            field=models.CharField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='fechaFinal',
            field=models.CharField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='fechainicio',
            field=models.CharField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.CharField(default=datetime.date.today),
        ),
    ]
