# Generated by Django 4.2.6 on 2023-10-16 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0020_alter_permisorutas_rolid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordentrabajo',
            old_name='usuario',
            new_name='jefeTaller',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='jefeTallerid',
        ),
    ]
