# Generated by Django 4.2.6 on 2023-10-16 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0021_rename_usuario_ordentrabajo_jefetaller_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='usuarioId',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='vehiculoId',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modulos.usuario'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='vehiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modulos.vehiculo'),
        ),
    ]
