# Generated by Django 4.2.6 on 2023-10-20 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0021_rename_subtotal_detalleventa_precio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='precio',
        ),
    ]
