# Generated by Django 4.2.6 on 2023-10-20 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0022_remove_detalleventa_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='precio',
            field=models.FloatField(null=True),
        ),
    ]
