# Generated by Django 4.2.6 on 2023-10-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0022_remove_cotizacion_usuarioid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
