# Generated by Django 4.2.6 on 2023-10-20 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0023_detalleventa_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='vehiculo',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='telefonoCliente',
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='apellido',
            field=models.CharField(default='a'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='correo',
            field=models.CharField(default='example@gmail.com', max_length=100),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='identificacion',
            field=models.IntegerField(default=1234567890),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='nombre',
            field=models.CharField(default='a'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='sucursal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modulos.sucursal'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='telefonoCliente',
            field=models.PositiveBigIntegerField(default=1234567890),
        ),
        migrations.AddField(
            model_name='venta',
            name='metodoPago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta de crédito'), ('transferencia', 'Transferencia bancaria'), ('cheque', 'Cheque')], default='efectivo'),
        ),
        migrations.AddField(
            model_name='venta',
            name='vehiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modulos.vehiculo'),
        ),
    ]
