# Generated by Django 4.2.6 on 2023-10-16 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0023_vehiculo_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='idUsuario',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='vendedor',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='vendedorId',
        ),
        migrations.AddField(
            model_name='venta',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modulos.usuario'),
        ),
    ]
