# Generated by Django 4.2.6 on 2023-10-20 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0024_remove_detalleventa_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentrabajo',
            name='estado',
            field=models.CharField(choices=[('recibida', 'Recibida'), ('en proceso', 'En proceso'), ('finalizado', 'Finalizado')], max_length=50),
        ),
    ]
