# Generated by Django 4.2.6 on 2023-10-16 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0025_remove_detalleventa_nombrevehiculo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventariorepuesto',
            name='repuestoId',
        ),
        migrations.RemoveField(
            model_name='inventariorepuesto',
            name='sucursalId',
        ),
        migrations.AddField(
            model_name='inventariorepuesto',
            name='repuesto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modulos.repuesto'),
        ),
        migrations.AddField(
            model_name='inventariorepuesto',
            name='sucursal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modulos.sucursal'),
        ),
    ]
