# Generated by Django 4.2.6 on 2023-10-24 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0026_rename_precio_venta_preciototal_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleventa',
            options={},
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='usuario',
            field=models.ForeignKey(limit_choices_to={'rol__id': 1}, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulos.usuario'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='precioUnitario',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='venta',
            name='precioTotal',
            field=models.FloatField(blank=True, default=0.0, editable=False),
        ),
        migrations.AlterField(
            model_name='venta',
            name='vendedor',
            field=models.ForeignKey(limit_choices_to={'rol__id': 1}, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulos.usuario'),
        ),
        migrations.AlterModelTable(
            name='detalleventa',
            table=None,
        ),
    ]
