# Generated by Django 4.2.5 on 2023-11-05 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0028_alter_usuario_rol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='rol',
            new_name='rol_name',
        ),
    ]
