# Generated by Django 4.2.5 on 2023-11-05 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0029_rename_rol_usuario_rol_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='rol_name',
            new_name='rol',
        ),
    ]
