# Generated by Django 4.2.5 on 2023-11-12 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0030_rename_rol_name_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='vendedor',
            field=models.ForeignKey(limit_choices_to={'rol'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulos.usuario'),
        ),
    ]
