# Generated by Django 4.2.5 on 2023-11-12 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0031_alter_venta_vendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='vendedor',
            field=models.ForeignKey(blank=True, db_column='rol', null=True, on_delete=django.db.models.deletion.SET_NULL, to='modulos.usuario'),
        ),
    ]
