# Generated by Django 4.2.5 on 2023-11-12 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0032_alter_venta_vendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='vendedor',
            field=models.ForeignKey(limit_choices_to={'rol__id': 6}, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulos.usuario'),
        ),
    ]
