# Generated by Django 4.2.5 on 2023-11-12 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0034_alter_venta_vendedor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='vendedor',
            new_name='vendedor_name',
        ),
    ]
