# Generated by Django 4.2.5 on 2023-11-12 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0035_rename_vendedor_venta_vendedor_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='vendedor_name',
            new_name='vendedor',
        ),
    ]
