# Generated by Django 4.2.5 on 2023-11-13 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0037_rename_vendedor_venta_vendedorid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='vendedorid',
            new_name='vendedor_id',
        ),
    ]
