# Generated by Django 4.2.5 on 2023-11-13 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0038_rename_vendedorid_venta_vendedor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='vendedor_id',
            field=models.ForeignKey(limit_choices_to={'nombre': 7}, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulos.usuario'),
        ),
    ]
