# Generated by Django 4.2.5 on 2023-11-13 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0039_alter_venta_vendedor_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.AlterField(
            model_name='venta',
            name='vendedor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modulos.usuario'),
        ),
        migrations.AlterModelTable(
            name='usuario',
            table=None,
        ),
    ]
