# Generated by Django 4.2.5 on 2023-11-13 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0040_alter_usuario_options_alter_venta_vendedor_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name_plural': 'usuarios'},
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuarios',
        ),
    ]
