# Generated by Django 4.2.5 on 2023-11-13 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0042_venta_permiso_rutas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='permiso_rutas',
        ),
        migrations.AddField(
            model_name='venta',
            name='permiso_Ventas',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulos.permisorutas'),
        ),
    ]
