# Generated by Django 4.2.5 on 2023-11-13 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0043_remove_venta_permiso_rutas_venta_permiso_ventas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={},
        ),
        migrations.AlterField(
            model_name='venta',
            name='permiso_Ventas',
            field=models.OneToOneField(limit_choices_to={'idPermiso': 7}, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulos.permisorutas'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='vendedor_id',
            field=models.ForeignKey(limit_choices_to={'rol': 1}, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulos.usuario'),
        ),
    ]
