# Generated by Django 4.2.5 on 2023-11-13 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0044_alter_venta_options_alter_venta_permiso_ventas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='permiso_Cotizaciones',
            field=models.OneToOneField(limit_choices_to={'idPermiso': 7}, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulos.permisorutas'),
        ),
    ]
