# Generated by Django 4.2.5 on 2023-11-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0046_alter_permisorutas_options_rutas_descripcion_ruta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutas',
            name='descripcion_Ruta',
            field=models.CharField(default='sin rutas2', max_length=50),
        ),
    ]
