# Generated by Django 4.2.5 on 2023-11-19 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0048_remove_venta_vehiculo_detalleventa_vehiculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='permiso_Ventas',
        ),
    ]
