# Generated by Django 4.2.5 on 2023-11-19 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0049_remove_venta_permiso_ventas'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='respuestos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modulos.repuesto'),
        ),
    ]
