# Generated by Django 4.2.5 on 2023-11-19 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0050_detalleventa_respuestos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleventa',
            old_name='respuestos',
            new_name='repuestos',
        ),
    ]
