# Generated by Django 4.2.5 on 2023-11-20 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0051_rename_respuestos_detalleventa_repuestos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='img',
            field=models.URLField(),
        ),
    ]
