# Generated by Django 4.2.5 on 2023-11-20 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0052_alter_vehiculo_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleventa',
            old_name='precioUnitario',
            new_name='total_repuesto',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='repuestos',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='total',
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='cantidad_repuesto',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='cantidad_vehiculo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='repuesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulos.repuesto'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='total_vehiculo',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modulos.vehiculo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='img',
            field=models.URLField(max_length=300),
        ),
    ]
