# Generated by Django 4.2.5 on 2023-11-20 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0055_remove_detalleventa_cantidad_repuesto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='cantidad_repuesto',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='total_repuesto',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='cantidad_vehiculo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='total_vehiculo',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='venta',
            name='precioTotal',
            field=models.FloatField(blank=True, default=0.0, editable=False),
        ),
    ]
