# Generated by Django 4.2.5 on 2023-11-23 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0056_detalleventa_cantidad_repuesto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariorepuesto',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventariovehiculo',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
