# Generated by Django 4.2.5 on 2023-11-23 04:45

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0057_inventariorepuesto_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='precio_unitario_repuesto',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='precio_unitario_vehiculo',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='venta',
            name='precioTotal',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.0'), editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='venta',
            name='vendedor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modulos.usuario'),
        ),
        migrations.AlterModelTable(
            name='detalleventa',
            table='DetalleVenta',
        ),
    ]
