# Generated by Django 4.2.6 on 2023-11-24 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0061_remove_detalleventa_precio_unitario_repuesto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repuesto',
            name='img',
            field=models.CharField(default='sin imagen', max_length=300),
        ),
        migrations.AddField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('en proceso', 'En proceso'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='En proceso', max_length=50),
        ),
        migrations.AlterField(
            model_name='rutas',
            name='descripcion_Ruta',
            field=models.CharField(default='sin ruta', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='img',
            field=models.CharField(default='sin imagen', max_length=300),
        ),
    ]
