# Generated by Django 4.2.6 on 2023-11-24 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0062_repuesto_img_venta_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repuesto',
            name='unidades',
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='img',
            field=models.URLField(default='sin imagen', max_length=300),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='img',
            field=models.URLField(default='sin imagen', max_length=300),
        ),
    ]
