# Generated by Django 4.2.6 on 2023-11-24 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0063_remove_repuesto_unidades_alter_repuesto_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repuesto',
            name='img',
            field=models.CharField(default='sin imagen', max_length=100),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='img',
            field=models.CharField(default='sin imagen', max_length=100),
        ),
    ]
