# Generated by Django 4.2.5 on 2023-11-27 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0064_alter_repuesto_img_alter_vehiculo_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='precio_unitario_repuesto',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='precio_unitario_vehiculo',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='total_repuesto',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=20),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='total_vehiculo',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=20),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='img',
            field=models.TextField(default='sin imagen'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='img',
            field=models.TextField(default='sin imagen'),
        ),
        migrations.AlterModelTable(
            name='detalleventa',
            table='DetalleVenta',
        ),
    ]
