# Generated by Django 4.2.5 on 2023-12-09 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0065_detalleventa_precio_unitario_repuesto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('en proceso', 'En proceso'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado'), ('cotizacion', 'En proceso')], default='En proceso', max_length=50),
        ),
    ]
