# Generated by Django 4.2.5 on 2023-12-10 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0067_alter_venta_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='precio',
        ),
    ]
