# Generated by Django 4.2.5 on 2023-12-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0068_remove_cotizacion_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='color',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='img',
            field=models.TextField(default='sin imagen'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='marca',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='modelo',
            field=models.IntegerField(default='2023'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='nombre',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
