# Generated by Django 4.2.5 on 2023-12-10 22:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0070_alter_ordentrabajo_options_alter_ordentrabajo_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordentrabajo',
            options={'verbose_name_plural': 'OrdenTrabajo'},
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='fechaFinal',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='fechainicio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterModelTable(
            name='ordentrabajo',
            table='OrdenTrabajo',
        ),
    ]
