# Generated by Django 4.2.5 on 2023-12-10 22:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0071_alter_ordentrabajo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentrabajo',
            name='fechaFinal',
            field=models.CharField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='fechainicio',
            field=models.CharField(default=datetime.date.today),
        ),
    ]
