# Generated by Django 4.2.5 on 2023-12-10 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0072_alter_ordentrabajo_fechafinal_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordentrabajo',
            options={},
        ),
        migrations.AlterModelTable(
            name='ordentrabajo',
            table=None,
        ),
    ]
