# Generated by Django 4.2.5 on 2023-12-10 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0073_alter_ordentrabajo_options_alter_ordentrabajo_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordentrabajo',
            options={'verbose_name_plural': 'OrdenTrabajo'},
        ),
        migrations.AlterModelTable(
            name='ordentrabajo',
            table='OrdenTrabajo',
        ),
    ]
