# Generated by Django 4.2.5 on 2023-12-10 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0074_alter_ordentrabajo_options_alter_ordentrabajo_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentrabajo',
            name='fechaFinal',
            field=models.DateField(blank=True, null=True),
        ),
    ]
