# Generated by Django 4.2.5 on 2023-12-11 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0075_alter_ordentrabajo_fechafinal'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='identificacion_Cliente',
            field=models.IntegerField(default='123'),
        ),
    ]
